bt_navigator:
  ros__parameters:
    default_nav_to_pose_bt_xml: "$(find-pkg-share arena_simulation_setup)/configs/nav2/interplanners/ai_reference_only/interplanner_behaviour.xml"
    default_nav_through_poses_bt_xml: ""
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_rate_controller_bt_node
      - nav2_pipeline_sequence_bt_node
    error_code_names:
      - compute_path_error_code
