#! /usr/bin/env python
import argparse
import os
from pathlib import Path

from arena_simulation_setup.tree.World import World

parser = argparse.ArgumentParser(description='Touch world and regenerate its description.')
parser.add_argument('world_name', type=str, help='Name of the world to touch.')
parser.add_argument('--all', action='store_true', help='Modify all files, not just the map.')
args = parser.parse_args()

base_dir = os.getcwd()
if (arena_dir := os.environ.get('ARENA_DIR')) is not None:
    base_dir = os.path.join(arena_dir, 'arena_simulation_setup', 'worlds')
world = World(Path(os.path.join(base_dir, args.world_name)))
world.save(world.load(), map_only=not args.all)
