contestants:

  # ---- SocialNav ----
  # - name: SocialNav_1_path
  #   local_planner: dwb
  #   inter_planner: navigate_w_replanning_time
  #   agent_name: SocialNav_1_path
  #   goal_tolerance_radius: 2.5

  # ---- Urban Navigation (UrbanNav FiLM) ----
  # - name: UrbanNav_FiLM
  #   local_planner: dwb
  #   inter_planner: navigate_w_replanning_time
  #   agent_name: UrbanNav_FiLM
  #   goal_tolerance_radius: 2.5

  # ---- LeLan ----
  - name: LeLan_v1
    local_planner: dwb
    inter_planner: navigate_w_replanning_time
    agent_name: LeLan_latest
    goal_tolerance_radius: 2.5

  # ---- Baseline DWB (non-AI) ----
  # - name: DWB_Baseline
  #   local_planner: dwb
  #   inter_planner: navigate_w_replanning_time
  #   agent_name: ""
  #   goal_tolerance_radius: 2.5

  # ---- CityWalker ----
  # - name: CityWalker-v1
  #   local_planner: dwb
  #   inter_planner: navigate_w_replanning_time
  #   agent_name: CityWalker_last-v2
  #   goal_tolerance_radius: 2.5