stages:
# - config:
#     SCENARIO:
#       file: default_04
#   episodes: 1
#   map: hospital_1
#   robot: turtlebot
#   name: hospital_1_default_04_turtlebot
#   tm_obstacles: scenario
#   tm_robots: scenario
#   timeout: 180
# - config:
#     SCENARIO:
#       file: default_03
#   episodes: 2
#   map: hospital_1
#   robot: turtlebot
#   name: hospital_1_default_03_turtlebot
#   tm_obstacles: scenario
#   tm_robots: scenario
#   timeout: 180
# - config:
#     SCENARIO:
#       file: default_05
#   episodes: 2
#   map: hospital_1
#   robot: turtlebot
#   name: hospital_1_default_05_turtlebot
#   tm_obstacles: scenario
#   tm_robots: scenario
#   timeout: 180
- config:
    SCENARIO:
      file: default_00
  episodes: 1
  map: hospital_1
  robot: turtlebot
  name: hospital_1_default_00_turtlebot
  tm_obstacles: scenario
  tm_robots: scenario
  timeout: 180
# - config:
#     SCENARIO:
#       file: default_01
#   episodes: 2
#   map: hospital_1
#   robot: turtlebot
#   name: hospital_1_default_01_turtlebot
#   tm_obstacles: scenario
#   tm_robots: scenario
#   timeout: 240
# - config:
#     SCENARIO:
#       file: default_02
#   episodes: 2
#   map: hospital_1
#   robot: turtlebot
#   name: hospital_1_default_02_turtlebot
#   tm_obstacles: scenario
#   tm_robots: scenario
#   timeout: 180

