stages:
- config:
    SCENARIO:
      file: 01_triage_shift
  episodes: 5
  map: hospital_1
  robot: turtlebot
  name: hospital_1_01_triage_shift_turtlebot
  tm_obstacles: scenario
  tm_robots: scenario
  timeout: 180
- config:
    SCENARIO:
      file: 02_rowd_navigation
  episodes: 5
  map: hospital_1
  robot: turtlebot
  name: hospital_1_02_rowd_navigation_turtlebot
  tm_obstacles: scenario
  tm_robots: scenario
  timeout: 180
